name: companyeidc
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.4
  qr_code_scanner: ^1.0.1
  permission_handler: ^8.2.6
  auto_route: 3.2.0
  freezed_annotation: ^0.15.0
  fpdart: ^1.1.0
  injectable: ^1.5.0
  retrofit: 2.2.0
  json_annotation: ^4.3.0
  riverpod: ^1.0.0
  get_it: ^7.2.0
  flutter_riverpod: ^1.0.0
  flutter_hooks: ^0.18.1
  reactive_forms: ^14.2.0  # Updated version for intl compatibility
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.8
  gap: ^3.0.1
  flutter_svg: ^0.23.0+1
  loading_indicator: ^3.0.2
  event_bus: ^2.0.0
  badges: ^2.0.1
  firebase_core: ^2.27.1
  firebase_messaging: ^14.7.20
  firebase_analytics: ^10.8.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.2
  freezed: ^0.15.1+1
  flutter_lints: ^1.0.4
  json_serializable: ^6.0.1
  auto_route_generator: 3.2.0
  retrofit_generator: ^2.2.0
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/pngs/
    - assets/svgs/
  fonts:
    - family: primaryFont
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true

analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
