// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_w1ERYtZsESy6B-3f6MEUZI5dcQYGdYA',
    appId: '1:380162677855:web:8b58b996315b7be6be4fea',
    messagingSenderId: '380162677855',
    projectId: 'companyeidc',
    authDomain: 'companyeidc.firebaseapp.com',
    storageBucket: 'companyeidc.appspot.com',
    measurementId: 'G-GF8C9QF467',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC01qLn2WVQvfyGXlkIraCfbLhLbslpxGQ',
    appId: '1:380162677855:ios:22666290ad7b63e3be4fea',
    messagingSenderId: '380162677855',
    projectId: 'companyeidc',
    storageBucket: 'companyeidc.appspot.com',
    iosBundleId: 'ly.com.componyeidc.companyeidc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC01qLn2WVQvfyGXlkIraCfbLhLbslpxGQ',
    appId: '1:380162677855:ios:22666290ad7b63e3be4fea',
    messagingSenderId: '380162677855',
    projectId: 'companyeidc',
    storageBucket: 'companyeidc.appspot.com',
    iosBundleId: 'ly.com.componyeidc.companyeidc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_w1ERYtZsESy6B-3f6MEUZI5dcQYGdYA',
    appId: '1:380162677855:web:9a77e4211ee6a2cdbe4fea',
    messagingSenderId: '380162677855',
    projectId: 'companyeidc',
    authDomain: 'companyeidc.firebaseapp.com',
    storageBucket: 'companyeidc.appspot.com',
    measurementId: 'G-NS1NRWK8Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_wbQ2JVYoLTc5y8D33o5ocPq0GmNQYXU',
    appId: '1:380162677855:android:1721c4bc5822bad4be4fea',
    messagingSenderId: '380162677855',
    projectId: 'companyeidc',
    storageBucket: 'companyeidc.appspot.com',
  );

}